package decryptor

import "fmt"

// unpadPKCS7 removes PKCS7 padding from the decrypted data
// (generated by ChatGPT)
func unpadPKCS7(data []byte) ([]byte, error) {
	paddingLength := int(data[len(data)-1])
	if paddingLength > len(data) || paddingLength == 0 {
		return nil, fmt.Errorf("invalid padding size")
	}

	// Check that all the padding bytes are the same as the padding length
	for _, paddingByte := range data[len(data)-paddingLength:] {
		if int(paddingByte) != paddingLength {
			return nil, fmt.Errorf("invalid padding byte")
		}
	}

	return data[:len(data)-paddingLength], nil
}
